name: NoDiscounts
version: '4.0'
main: com.alan.noDiscounts.NoDiscounts
api-version: '1.21'
commands:
  nodiscounts:
    description: Toggle villager discounts on/off
    usage: /<command> <on|off>
    permission: nodiscounts.toggle
permissions:
  nodiscounts.toggle:
    description: Allows toggling villager discounts
    default: op